version: '3.9'
services:
  nginx-webclient:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./main/web:/usr/share/nginx/html/
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: mibquizzz
      MARIADB_USER: adminer
      MARIADB_PASSWORD: adminer
    ports:
      - "5555:3306"
    volumes:
      - ./main/java/de/gruppeo/wise2122_java_server/docker/mysql:/docker-entrypoint-initdb.d

  adminer:
      image: adminer:latest
      container_name: adminer
      depends_on:
        - mariadb
      restart: always
      environment:
        ADMINER_DEFAULT_SERVER: mariadb
        ADMINER_DEFAULT_DB_DRIVER: mysql
        ADMINER_DEFAULT_DB_HOST: mariadb
        ADMINER_DEFAULT_DB_NAME: mibquizzz
        ADMINER_DESIGN: nette
        ADMINER_PLUGINS: tables-filter tinymce
      ports:
        - "7777:8080"